---
- name: install nginx
  yum: name=nginx state=present

- name: setting api loadbalance
  copy: 
    src={{ item }}
    dest=/etc/nginx/conf.d/api-server.conf
    owner=root
    group=root
    mode=0644
  with_fileglob:
    - api-server.conf
    - etcd.conf
  when: clusterd | default(False) == True

- name: systemcd enable nginx
  systemd:
    name=nginx
    state=started
    enabled=yes

