---
- name: disable selinux
  selinux:
    state=disabled

- name: disable NetworkManager
  systemd:
    name=NetworkManager
    state=stopped
    enabled=no

- name: disable firewalld
  systemd:
    name=firewalld
    state=stopped
    enabled=no

- name: set hosts file
  lineinfile:
    dest=/etc/hosts
    state=present
    line='{{ item.ipaddr }}  {{ item.name }}'
  with_items: hosts_params


