---
- name: disable selinux
  selinux:
    state=disabled

- name: disable NetworkManager
  systemd:
    name=NetworkManager
    state=stopped
    enabled=no

- name: disable firewalld
  systemd:
    name=firewalld
    state=stopped
    enabled=no

- name: set hosts file
  lineinfile:
    dest=/etc/hosts
    state=present
    line='{{ item.ipaddr }}  {{ item.name }}'
  with_items: hosts_params

- name: install docker packages
  yum: name=docker state=present

- name: add overlay to modprobe.conf
  lineinfile:
    dest=/etc/modules-load.d/overlay.conf
    line='overlay'
    create=yes

- name: load overlay kernel module
  modprobe:
    name=overlay
    state=present

- name: set overlay docker storage driver
  lineinfile:
    dest=/etc/sysconfig/docker-storage-setup
    line='STORAGE_DRIVER="overlay"'

- name: systemcd enable docker
  systemd:
    name=docker
    state=started
    enabled=yes 

