---
- name: create kubernetes log directory
  file:
    path=/var/log/kubernetes
    state=directory
    owner=kube
    group=kube
    mode=0755

- name: setting kubernetes bese
  template: 
    src=kubernetes_config.j2
    dest=/etc/kubernetes/config
    owner=root
    group=root
    mode=0644

- name: setting flanneld
  template: 
    src=flanneld.j2
    dest=/etc/sysconfig/flanneld
    owner=root
    group=root
    mode=0644

- name: systemcd enable flanneld
  systemd:
    name=flanneld
    state=started
    enabled=yes 

