---
- name: setting kube-apiserver
  template: 
    src=apiserver.j2
    dest=/etc/kubernetes/apiserver
    owner=root
    group=root
    mode=0644

- name: systemcd enable kube-apiserver
  systemd:
    name=kube-apiserver
    state=started
    enabled=yes 

- name: systemcd enable kube-controller-manager
  systemd:
    name=kube-controller-manager
    state=started
    enabled=yes 

- name: systemcd enable kube-scheduler
  systemd:
    name=kube-scheduler
    state=started
    enabled=yes 

