---
- name: install master packages
  yum: name={{ item }} state=present
  with_items:
  - kubernetes-master
  - etcd
  - flannel

- name: setting clustered etcd
  file:
    path=/etc/etcd/etcd.conf
    state=absent

- name: setting clustered etcd
  blockinfile:
    dest=/etc/etcd/etcd.conf
    content='ETCD_NAME={{ inventory_hostname_short }}\n
    ETCD_DATA_DIR="/var/lib/etcd/default.etcd"\n
    ETCD_LISTEN_PEER_URLS="http://{{ mngip }}:2380"\n
    ETCD_LISTEN_CLIENT_URLS="http://{{ mngip }}:2379,http://127.0.0.1:2379"\n
    ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ mngip }}:2380"\n
    ETCD_INITIAL_CLUSTER="{{ clustermember }}"\n
    ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"\n
    ETCD_ADVERTISE_CLIENT_URLS="http://{{ mngip }}:2379"'
    create=yes
  when: clusterd | default(False) == True

- name: setting clustered etcd new
  lineinfile:
    dest=/etc/etcd/etcd.conf
    state=present
    line='ETCD_INITIAL_CLUSTER_STATE="new"'
  run_once: true
  when: clusterd | default(False) == True

- name: setting unclustered etcd
  blockinfile:
    dest=/etc/etcd/etcd.conf
    content='ETCD_NAME=default\n
    ETCD_DATA_DIR="/var/lib/etcd/default.etcd"\n
    ETCD_LISTEN_PEER_URLS="http://localhost:2380"\n
    ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"\n
    ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"\n'
    create=yes
  when: clusterd | default(False) == False

- name: systemcd enable etcd
  systemd:
    name=etcd
    state=started
    enabled=yes

- name: check etcd setting for flannel
  shell: etcdctl get /kube-centos/network/config
  register: result
  changed_when: False
  ignore_errors: True

- name: setting etcd for flannel
  shell: >
    etcdctl mkdir /kube-centos/network;
    etcdctl mk /kube-centos/network/config '{ "Network": "172.30.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan" } }'
  run_once: true
  when: result.stderr.find("Key not found") != -1


