---
- name: install master packages
  yum: name={{ item }} state=present
  with_items:
  - kubernetes-master
  - etcd
  - flannel

- name: setting clustered etcd
  blockinfile:
    dest=/etc/etcd/etcd.conf
    content='ETCD_NAME={{ inventory_hostname_short }}
      ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
      ETCD_LISTEN_PEER_URLS="http://{{ mngip }}:2380"
      ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
      ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ mngip }}:2380"
      ETCD_INITIAL_CLUSTER="{{ clustermember }}"
      ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
      ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"'
  when: clusterd | default(False) == True

- name: setting clustered etcd new
  lineinfile:
    dest=/etc/etcd/etcd.conf
    state=present
    line='ETCD_INITIAL_CLUSTER_STATE="new"'
  run_once: true
  when: clusterd | default(False) == True

- name: systemcd enable etcd
  systemd:
    name=etcd
    state=started
    enabled=yes

- name: setting etcd for flannel
  shell: >
    etcdctl mkdir /kube-centos/network;
    etcdctl mk /kube-centos/network/config 
      '{ "Network": "172.30.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan" } }'


